name: Setup
description: Checkout code, setup Bun, and install dependencies

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Setup Bun
      uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3
    - name: Install dependencies
      run: bun install
      shell: bash
