services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-push:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: bun run db:push
    restart: "no"

  s3-push:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - AWS_S3_URL=http://localstack:4566
      - AWS_ACCESS_ID=test
      - AWS_ACCESS_SECRET=test
      - AWS_S3_REGION=us-west-1
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      localstack:
        condition: service_healthy
    command: bun src/lib/s3/push.ts
    restart: "no"

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=http://localhost:3000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - AWS_S3_URL=http://localstack:4566
      - AWS_ACCESS_ID=test
      - AWS_ACCESS_SECRET=test
      - AWS_S3_REGION=us-west-1
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-ysI0G5Rbw3y8ubK0VQjvplLyRCVrHfjm}
      - BETTER_AUTH_URL=http://localhost:3000
      - NEXT_TELEMETRY_DISABLED=1
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_healthy
    restart: unless-stopped

  db-studio:
    build:
      context: .
      dockerfile: Dockerfile.studio
    ports:
      - "4983:4983"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  data:
