[build]
  secretsScanOmitKeys = ["NEXT_PUBLIC_GOOGLE_MAPS_API_KEY"]

[context.production]
  command = "npm run build:prod"

[context.branch-deploy]
  command = "npm run build:beta"

[context.deploy-preview]
  command = "npm run build:beta"
