'use client'

import { useEffect, useState } from 'react'
import { v4 as uuidv4 } from 'uuid'
import { Entity } from '@/lib/db/schema'
import { Review } from '@/lib/types'
import IndicatorDisplay from './reviews/indicator-display'

interface AIOverviewProps {
  entity: Entity
  reviews: Review[]
  indicators: Indicator[]
  given: string
}

interface Indicator {
  id: string
  reviewId: string
  indicator: string
  exists: boolean | null
}

export default function AIOverview({
  entity,
  reviews,
  indicators,
  given,
}: AIOverviewProps) {
  const [overview, setOverview] = useState<string>('')
  const [entityIndicators, setEntityIndicators] = useState<Indicator[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)

  useEffect(() => {
    async function fetchOverview() {
      try {
        const overviewRes = await fetch('/api/entity/groq/overview/', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            entity,
            reviews,
            indicators,
            given,
          }),
        })

        if (!overviewRes.ok) {
          throw new Error('Failed to fetch overview')
        }

        const overviewJson = await overviewRes.json()
        let parsedResponse

        try {
          parsedResponse = JSON.parse(overviewJson.message)
        } catch (parseError) {
          console.error('Failed to parse overviewJson.message:', parseError)
          parsedResponse = {
            overview:
              'There was an error with the AI response. Please try again later.',
            indicators: [],
          }
        }

        setOverview(parsedResponse.overview)

        const aiIndicators = parsedResponse.indicators.map(
          (indicator: { indicator: string; exists: boolean }) => ({
            id: uuidv4(),
            reviewId: '',
            indicator: indicator.indicator,
            exists: indicator.exists,
          }),
        )

        aiIndicators.sort((a: { exists: boolean }, b: { exists: boolean }) => {
          if (a.exists < b.exists) return 1
          if (a.exists > b.exists) return -1
          return 0
        })

        setEntityIndicators(aiIndicators)
      } catch (err) {
        console.error('Error fetching AI overview:', err)
        setError(true)
        setOverview(
          'Unable to load AI overview at this time. Please try again later.',
        )
      } finally {
        setLoading(false)
      }
    }

    fetchOverview()
  }, [entity, reviews, indicators, given])

  if (loading) {
    return (
      <div>
        <div className="mb-2 animate-pulse">
          <div className="mb-2 h-4 rounded bg-gray-200 dark:bg-gray-700"></div>
          <div className="mb-2 h-4 rounded bg-gray-200 dark:bg-gray-700"></div>
          <div className="h-4 w-3/4 rounded bg-gray-200 dark:bg-gray-700"></div>
        </div>
        <div className="mt-4 space-y-2">
          <div className="h-8 w-full rounded bg-gray-200 dark:bg-gray-700"></div>
          <div className="h-8 w-full rounded bg-gray-200 dark:bg-gray-700"></div>
          <div className="h-8 w-full rounded bg-gray-200 dark:bg-gray-700"></div>
        </div>
        <p className="mt-1 text-xs text-gray-500">
          Loading AI-generated overview...
        </p>
      </div>
    )
  }

  return (
    <div>
      <p className="mb-2">{overview}</p>
      {!error && <IndicatorDisplay indicators={entityIndicators} />}
      <p className="mt-1 text-xs">
        This overview was generated by AI and may be inaccurate
      </p>
    </div>
  )
}
