import { db } from "@/db";
import { reviewIndicatorTable, reviewTable } from "@/db/schema";
import { eq, inArray } from "drizzle-orm";
import { Entity } from "@/db/schema";
import ReviewDisplay from "./review-display";
import CustomLink from "./custom-link";
import { Button } from "./ui/button";

export default async function EntityDisplay({
  googleId,
}: {
  googleId: string;
}) {
  const res = await fetch(
    `${process.env.URL}/api/entity/?googleId=${googleId}`,
  );
  const rawData = await res.json();
  const data: Entity = rawData[0];
  const given = data.description || "";
  let overview = "";
  // Fetch reviews and indicators for this entity
  const reviews = await db
    .select()
    .from(reviewTable)
    .where(eq(reviewTable.entityId, data.id));

  const reviewIds = reviews.map((review) => review.id);

  const indicators = reviewIds.length
    ? await db
        .select()
        .from(reviewIndicatorTable)
        .where(inArray(reviewIndicatorTable.reviewId, reviewIds))
    : [];

  // Call AI overview API with entity, reviews, and indicators
  const overviewRes = await fetch(
    `${process.env.URL}/api/entity/groq/overview/`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        entity: data,
        reviews: reviews,
        indicators: indicators,
        given: given,
      }),
    },
  );
  const overviewJson = await overviewRes.json();
  overview = overviewJson.message || overviewJson;

  return (
    <div>
      <p>{data?.displayType}</p>
      <h2>Overview</h2>
      <p>{overview}</p>
      <p
        className="text-xs
      "
      >
        This overview was generated by AI and may be inaccurate
      </p>
      <h2>Address</h2>
      <p>
        {data?.address1}
        <br />
        {data?.address2 && (
          <>
            {data?.address2}
            <br />
          </>
        )}
        {data?.city}, {data?.state} {data?.zip}
        <br />
        {data?.country}
      </p>
      {data?.address1 && data?.city && data?.country && (
        <a
          href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${data.address1}${data.address2 ? " " + data.address2 : ""}, ${data.city}, ${data.state ? data.state + " " : ""}${data.zip ? data.zip + " " : ""}${data.country}`)}`}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-block py-2"
        >
          <Button variant="secondary">Get Directions</Button>
        </a>
      )}
      <h2 className="mt-4">Website</h2>
      <CustomLink href={data?.url || " "} underline>
        {data?.url}
      </CustomLink>

      {data?.hours.length > 0 && (
        <>
          <h2>Hours</h2>
          <ul>
            {data?.hours?.map((hour: string, index: number) => (
              <li key={index}>{hour}</li>
            ))}
          </ul>
          <p className="text-xs">Timezone: {data?.timeZone}</p>{" "}
        </>
      )}
      <ReviewDisplay
        entity_id={data.id}
        entity_type={data?.type}
        reviews={reviews}
        indicators={indicators}
      />
    </div>
  );
}
