import { db } from "@/db";
import { reviewIndicatorTable, reviewTable } from "@/db/schema";
import { eq, inArray } from "drizzle-orm";
import { Entity } from "@/db/schema";
import Link from "next/link";
import ReviewDisplay from "./review-display";

export default async function EntityDisplay({
  googleId,
}: {
  googleId: string;
}) {
  const res = await fetch(
    `${process.env.URL}/api/entity/?googleId=${googleId}`,
  );
  const rawData = await res.json();
  const data: Entity = rawData[0];
  let overview = "";
  // Fetch reviews and indicators for this entity
  const reviews = await db
    .select()
    .from(reviewTable)
    .where(eq(reviewTable.entityId, data.id));

  const reviewIds = reviews.map((review) => review.id);

  const indicators = reviewIds.length
    ? await db
        .select()
        .from(reviewIndicatorTable)
        .where(inArray(reviewIndicatorTable.reviewId, reviewIds))
    : [];

  // Call AI overview API with entity, reviews, and indicators
  const overviewRes = await fetch(
    `${process.env.URL}/api/entity/groq/overview/`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        entity: data,
        reviews: reviews,
        indicators: indicators,
      }),
    },
  );
  const overviewJson = await overviewRes.json();
  overview = overviewJson.message || overviewJson;

  return (
    <div>
      <h2>{data?.displayType}</h2>
      <p>{data?.description}</p>
      <h2 className="mt-2">Overview</h2>
      <p>{overview}</p>
      <p className="text-xs">
        This overview was generated by AI and may be inaccurate
      </p>
      <h2 className="mt-2">Address</h2>
      <p>{data?.address1}</p>
      <p>{data?.address2}</p>
      <p>
        {data?.city}, {data?.state} {data?.zip}
      </p>
      <p>{data?.country}</p>
      <h2 className="mt-2">Website</h2>
      <Link href={data?.url || " "}>
        <p className="underline">{data?.url}</p>
      </Link>
      {data?.hours.length > 0 && (
        <>
          <h2 className="mt-2">Hours</h2>
          <ul>
            {data?.hours?.map((hour: string, index: number) => (
              <p key={index}>{hour}</p>
            ))}
          </ul>
          <p className="text-xs mt-1">Timezone: {data?.timeZone}</p>{" "}
        </>
      )}
      <ReviewDisplay
        entity_id={data.id}
        entity_type={data?.type}
        reviews={reviews}
        indicators={indicators}
      />
    </div>
  );
}
