import { Entity } from "@/db/schema";
import Link from "next/link";
import ReviewDisplay from "./review-display";

export default async function EntityDisplay({
  googleId,
}: {
  googleId: string;
}) {
  const res = await fetch(
    `http:/localhost:3000/api/entity?googleId=${googleId}`,
  );
  const rawData = await res.json();
  const data: Entity = rawData[0];

  return (
    <div>
      <h2>{data?.displayType}</h2>
      <p>{data?.description}</p>
      <h2 className="mt-2">Overview</h2>
      <p className="md:max-w-[50%]">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
        velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
        occaecat cupidatat non proident, sunt in culpa qui officia deserunt
        mollit anim id est laborum.
      </p>
      <p className="text-xs">
        This overview was generated by AI and may be inacurrate
      </p>
      <h2 className="mt-2">Address</h2>
      <p>{data?.address1}</p>
      <p>{data?.address2}</p>
      <p>
        {data?.city}, {data?.state} {data?.zip}
      </p>
      <p>{data?.country}</p>
      <h2 className="mt-2">Website</h2>
      <Link href={data?.url || " "}>
        <p className="underline">{data?.url}</p>
      </Link>
      <h2 className="mt-2">Hours</h2>
      <ul>{data?.hours?.map((hour, index) => <p key={index}>{hour}</p>)}</ul>
      <p className="text-xs mt-1">Timezone: {data?.timeZone}</p>
      <ReviewDisplay entity_id={data.id} entity_type={data?.type} />
    </div>
  );
}
