name: Biome

on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta

jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Setup
        uses: ./.github
      - name: Format code
        run: bun format
      - name: Lint code
        run: bun lint
