name: Next.js

on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Setup
        uses: ./.github
      - name: Attempt build
        run: bun run build
        env:
          BETTER_AUTH_URL: http://localhost:3000
          BETTER_AUTH_SECRET: 2Ws16mRlS0u5Oau8P6WFSBASY45w47zL
          NEXT_TELEMETRY_DISABLED: 1
