name: Cypress

on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:22-alpine
    services:
      db:
        image: postgres:17.4
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: npm install

        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

