name: Cypress

on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta

jobs:
  e2e:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-24.04
    container: cypress/browsers:node-22.15.0-chrome-136.0.7103.92-1-ff-138.0.1-edge-136.0.3240.50-1
    env:
      DATABASE_URL: postgres://postgres:postgres@db:5432/db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      BASE_URL: http://localhost:3000
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      BETTER_AUTH_URL: http://localhost:3000
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    services:
      db:
        image: postgres:17.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install

      - name: Push database schema
        run: bun db:push

      - name: Seed database
        run: bun db:seed

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: bun dev
          browser: chrome
          record: true
