name: Cypress

on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta

jobs:
  e2e:
    runs-on: ubuntu-latest
    container: node:22-alpine
    services:
      db:
        image: postgres:17.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm install

      - name: Seed database
        run: npm run db:seed
        env:
          DATABASE_URL: postgres://postgres:postgres@db:5432/db

      - name: Run Cypress tests
        run: npm run test:e2e
        env:
          DATABASE_URL: postgres://postgres:postgres@db:5432/db
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
