name: Mention Assignee On Issue Assignment

on:
  issues:
    types: [assigned]

jobs:
  mention-assignee:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Comment mentioning assignee
        uses: actions/github-script@v7
        with:
          script: |
            const assignee = context.payload.assignee.login;
            const issue_number = context.payload.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const comment = `Hey @${assignee}, you have just been assigned to this issue! Please leave a comment if you run into any problems with working on this issue. Please also consider starring this repository so others can find it more easily`;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: comment
            });
