name: Playwright
on:
  push:
    branches: beta
  pull_request:
    branches: beta
jobs:
  Test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-noble
    permissions:
      contents: read
    env:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    services:
      db:
        image: postgres:18.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3
      - name: Install dependencies
        run: bun install
      - name: Push database schema
        run: bun run db:push
      - name: Run Playwright tests
        run: bunx playwright test
