name: Playwright

on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta

jobs:
  Test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
    services:
      db:
        image: postgres:18.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Setup
        uses: ./.github
      - name: Push database schema
        run: bun run db:push
      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: Run Playwright tests
        run: bunx playwright test
