name: Prettier

on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta

jobs:
  Format:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Format code
        run: npm run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403
        with:
          commit_message: Formatted code with Prettier [skip ci]
          commit_author: Author <41898282+github-actions[bot]@users.noreply.github.com>
          branch: ${{ github.head_ref || github.ref_name }} # supports both push and PR
          create_branch: true
