name: Prettier

on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta

jobs:
  Format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Check code formatting
        run: npm run format
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Formatted code with Prettier
        
    
